name: flutter_liquid_glass
description: Liquid Glass Effect for Flutter
version: 0.1.0


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.3.1
  mocktail: ^1.0.3

flutter:
  shaders:
    - lib/assets/shaders/shapes.frag
    - lib/assets/shaders/displacement.frag
